/**
 * The screens a user sees before any work happens: what the tool can do, what
 * version it is, and why an invocation was refused.
 *
 * These are the most-read surfaces MAGI has, and they were the last ones the
 * renderer touched. `magi` with no arguments, `magi help` and `--version` were
 * raw writes, so the first thing anyone saw was the one thing that had not
 * changed. That is not a decoration decision a command layer gets to make, so
 * it is made here, once, by the same terminal question everything else asks.
 *
 * The pipe is what keeps the plain path: `--version` is parsed by whatever
 * asked for it, and the command screens are read as text, carried into
 * README.md verbatim and asserted there byte for byte. Both must arrive whole,
 * without a bar down the side. So the bytes a pipe receives are assembled here
 * too, from the same parts the drawn screen is built from, rather than kept as
 * a second string beside them where the two would drift.
 */

import { box, cancel, intro, note } from "@clack/prompts";

import { decorated, errStream, outStream } from "./streams.ts";
import { close, detail, open, plain, plainError, problem } from "./write.ts";

/**
 * What one command costs, in the categories a reader has to be told about
 * before they run it. Every field is prose, and every field is optional: what
 * makes one obligatory is the flags the command declares, which is a rule
 * `test/spec/notes.test.ts` holds each command to.
 *
 * The categories are not decoration. They are what the generated screen cannot
 * say: commander knows a flag exists and what it is called, and knows nothing
 * about what it spends, what it refuses, what it writes down, or which part of
 * the decision was never the tool's to make.
 */
export interface CommandNote {
  /** What running it costs, and when it asks first. */
  readonly spends?: string;
  /** What it refuses to do, and what the user says to override the refusal. */
  readonly refuses?: string;
  /** What it writes down: the ledger, the disk, somebody else's HOME. */
  readonly records?: string;
  /** The part of the decision that stays with the user. */
  readonly decides?: string;
}

/** The categories in the order they are read, with the word each is drawn as. */
const CATEGORIES: ReadonlyArray<readonly [keyof CommandNote, string]> = [
  ["spends", "spends"],
  ["refuses", "refuses"],
  ["records", "records"],
  ["decides", "decides"],
];

export interface UsageScreen {
  /** The command list, generated by the parser from what each command takes. */
  readonly commands: string;
  /** Where the prose went: the line that sends a reader to the command. */
  readonly pointer: string;
}

/**
 * The whole screen as one block, which is what a pipe receives.
 *
 * The prose that used to run on under this block now lives on each command's
 * own screen, beside the flags it is about, and what is left here is the line
 * that says so. A piped orchestrator reads this screen first, so the line is
 * load-bearing rather than a courtesy.
 */
export function usageText(screen: UsageScreen): string {
  return `${screen.commands}\n\n${screen.pointer}`;
}

/** One command's note as a pipe receives it: a labelled paragraph each. */
export function noteText(about: CommandNote): string {
  return CATEGORIES.filter(([key]) => about[key] !== undefined)
    .map(([key, label]) => `${label}: ${about[key] as string}`)
    .join("\n\n");
}

/** What the tool can do: `magi help`, `magi --help`, and `magi` with nothing. */
export function usage(screen: UsageScreen): void {
  if (!decorated(outStream())) {
    plain(usageText(screen));
    return;
  }
  open("magi");
  // Sized to the table rather than to the terminal: the default stretches a
  // box to the full width, which puts the flags at one edge and the frame at
  // the other with a hand's width of nothing between them.
  box(screen.commands, "usage", { output: outStream(), width: "auto" });
  detail(screen.pointer);
  close("the council thinks; the orchestrator works");
}

/**
 * One command's own screen: what `magi review --help` prints.
 *
 * The text is generated by the parser from the flags that command declares, so
 * nothing here decides what it says; what is decided here is the same thing
 * every other screen decides, which is how much of it is drawn.
 */
export function commandUsage(text: string, about: CommandNote = {}): void {
  const prose = noteText(about);
  if (!decorated(outStream())) {
    plain(prose === "" ? text : `${text}\n\n${prose}`);
    return;
  }
  open("magi");
  box(text, "usage", { output: outStream(), width: "auto" });
  // One note per category rather than one wall of prose: what a command costs
  // and what it refuses are two different questions, and run together nobody
  // reads past the first.
  for (const [key, label] of CATEGORIES) {
    const body = about[key];
    if (body !== undefined) note(body, label, { output: outStream() });
  }
  close("magi help lists every command");
}

/**
 * The same refusal for one command rather than for the tool: the screen that
 * command prints, on the stream a pipeline reads separately.
 *
 * The root screen names the commands and not their flags, so a caller that
 * got a consult's grammar wrong and read the refusal down a pipe was handed
 * a list that could not tell it what it had got wrong.
 *
 * The screen and nothing else: what a command costs is read before it is run,
 * and stderr on this path is what a pipeline greps for the reason it failed.
 */
export function refuseCommand(text: string, reason?: string): void {
  if (!decorated(errStream())) {
    plainError(text);
    return;
  }
  intro("magi", { output: errStream() });
  if (reason !== undefined) problem(reason);
  box(text, "usage", { output: errStream(), width: "auto" });
  cancel("magi help explains each command", { output: errStream() });
}

/**
 * The version, and nothing around it where it is being parsed.
 *
 * The exact-compare in the end-to-end suite is the contract: a bar or a colour
 * around this number is a break that only a whole-string assertion can see.
 */
export function version(value: string): void {
  if (!decorated(outStream())) {
    plain(value);
    return;
  }
  open("magi");
  detail(value);
  close("magi help lists what it can do");
}

/**
 * The invocation itself was wrong, so the block goes to stderr and the caller
 * gets exit 2. A pipeline reading stdout for a result must not receive this as
 * one.
 *
 * A reason given here is drawn on a terminal only. What a pipe receives on
 * this path is a byte contract older than this renderer: the block alone, with
 * nothing before it. A command that wants its reason on both paths says so
 * with `problem` before calling this, which is what the subcommands do.
 */
export function refuseUsage(screen: UsageScreen, reason?: string): void {
  if (!decorated(errStream())) {
    plainError(usageText(screen));
    return;
  }
  // Opened on stderr rather than through `open`, because every line of this
  // screen belongs on the stream a pipeline reads separately, and a bar that
  // `cancel` closes without anything having opened it hangs off nothing.
  intro("magi", { output: errStream() });
  if (reason !== undefined) problem(reason);
  box(screen.commands, "usage", { output: errStream(), width: "auto" });
  cancel("magi help explains each command", { output: errStream() });
}
